spring:
  data:
    mongodb:
      uri: mongodb://mongo:tqkVucRmmlofwwKvuRcygPFvhfwNDMRt@crossover.proxy.rlwy.net:53586/journaldb
      auto-index-creation: true

server:
  port: ${PORT:8080}

